### ISSUE TITLE
BaseConfig.py: stop using deprecated optparse Python module.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hpstr#106]
BaseConfig uses "optparse" which is deprecated since Python 3.2 (in 2011). Use argparse instead.

Also:  Permit multiple input files, not just one.

**Comment by cbravo135** [comment]
Since we intend to use pyROOT, which does not yet have full python3 support, calling "optparse" deprecated is a strong use of the term. Also, there is again no need to require multiple input files, just run each file separately in parallel. It is faster to run this way anyway.

**Comment by mholtrop** [comment]
Read the doc: https://docs.python.org/2/library/optparse.html

Deprecated since version 2.7: The optparse <https://docs.python.org/2/library/optparse.html#module-optparse> module is deprecated and will not be developed further; development will continue with the argparse <https://docs.python.org/2/library/argparse.html#module-argparse> module.

**Comment by cbravo135** [comment]
I am aware of the situation. My point is that when using hpstr, you probably will find yourself using python 2.7 if you try to do any real work since root doesn't play super well with python3 yet. Since the users are probably using 2.7 anyway for now (until ROOT has better python3 support) this issue isn't huge. Switching from optparse to argparse is gonna take some effort. I would argue that in principle we are fine using optparse as is and are not necessarily interested in any further developments going into argparse. I don't disagree in principle with moving towards better supporting python3, just saying we probably should wait on building 32 to make progress before we make this push.

**Comment by mholtrop** [comment]
The argparse module works perfectly well with Python2.7 and I really doubt anyone would want to use version 2.6 of Python, which is now more than a decade old. The switch to argparse is totally simple. So why is there this resistance to improve the code?

Besides, ROOT works perfectly well with Python3.

**Comment by cbravo135** [comment]
This is not resistance, but just be aware that this would be rather low on my personal priority list. If someone has time to do it, they should feel free. This is just gonna take small changes to all the cfg.py files, so while the changes are simple, there is just a decent sized volume of them.

**Comment by mholtrop** [comment]
It is mostly a change to baseConfig.py. It then allows for a lot more flexibility in arguments. 
There aren't that many cfg.py files yet.
