### ISSUE TITLE
Running hpstr with only 2 arguments at run time

### ISSUE THREAD

**Issue by pbutti** [JeffersonLab/hpstr#23]
The functionality of running hpstr with just the configuration file, i.e.
 hpstr config.py
is broken in the current master branch. 
In the case we would like to run hpstr where the input files are already defined in the config files (for example using glob) we need to add a third argument for the parser to work i.e
 hpstr config.py dummy
Can the parser be fixed to make it possible to run with only specifying the configuration?

**Comment by cbravo135** [comment]
The desired behavior at runtime is to have 2 or more arguments. The configuration step fails in the case of having exactly two arguments at runtime.

**Comment by mholtrop** [comment]
The issue was with the n>0 test, which tested the number of arguments given to the script. This needed to be removed so that the sys.argv is set even when there are no arguments given. sys.argv[0] in Python holds the name of the script.

Please test iss23 branch on your configuration, and if it now works as expected, merge the pull.

**Comment by cbravo135** [comment]
Fixed by PR [25](https://github.com/JeffersonLab/hpstr/pull/25)
