### ISSUE TITLE
Compile against python3

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hpstr#6]
Python 2.7 will no longer be maintained beyond 2020. We should also support python3.

**Comment by mholtrop** [comment]
I am 90% there for making hpstr compatible with Python3. 
Just debugging an oddity with ConfigurePython.cxx and the arguments it receives.

**Comment by omar-moreno** [comment]
Great!  Where are you pushing code to?

**Comment by mholtrop** [comment]
I am working on my own repo https://github.com/mholtrop/hpstr.git on the alt_python3 branch, because I “pollute” the branch with an Xcode configuration file.

The issue I am having with the code right now is the following subtle bug. Subtle because I don’t understand what is going on :-)

The hpstr.cxx code initiates ConfigurePython() with:

       ConfigurePython cfg(argv[ptrpy], argv + ptrpy + 1, argc - ptrpy);

And I think this is wrong. If there are 3 things in argv, i.e. [‘hpstr’,’dst.py’,’infile.slcio’] then argv+ptrpy+1 will be pointing to ‘infield.slcio’, but argc-ptrpy will be 2. It should be 1.

In ConfigurePython.cxx in the code that uses this info:

     char** targs = new char*[nargs + 1];
      targs[0] = (char*) python_script.c_str();
      for (int i = 0; i < nargs; i++)
          targs[i + 1] = args[i];

      PySys_SetArgvEx(nargs, targs, 1);

If you add a “std::cout<< args[i] << std::endl;” before the targs[i+1] the code will crash because nargs is 2. 
However, if I “fix” the call, and thus have nargs = 1, then this routine crashes on exit. 

First question: Do you agree that we should instantiate ConfigurePython with argc - ptrpy -1 ?
Second question: Any clue why there is a crash when I do that?

Still debugging more…..

**Comment by mholtrop** [comment]
I found the problem I mention above. The code crashed because I needed to then change the count to `PySys_SetArgvEx(nargs+1)`.

The changes were pushed to the branch iss6. Made pull request.

**Comment by cbravo135** [comment]
Resolved by PR #8
